### ISSUE TITLE
Reimplemented out commented methods

### ISSUE THREAD

**Issue by pchschulz** [restruct/silverstripe-namedlinkfield#8]
There are a lot of methods in this module, which are commented out, especially in file "NamedLinkField.php". F.e. the method "getURL()", for outputting a link to a template. Without this method I have to build the link myself, each time I want to use it in a template.

I think most of this methods have been implemented in version 1.* of this module. I was wondering, why they have been removed in the second version for ss4.

**Comment by micschk** [comment]
In the current SS4 version this functionality has all ben restored.
